# Generated by Django 4.1.4 on 2022-12-29 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_order', models.CharField(max_length=255, verbose_name='Замовлення')),
                ('phone_user', models.CharField(max_length=15, verbose_name='Номер користувача')),
                ('individual_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Ідентифікатор замовлення')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
