# Generated by Django 4.1.4 on 2023-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_good', models.CharField(max_length=255, verbose_name='Товари')),
                ('description', models.TextField(verbose_name='Опис товару')),
                ('image', models.TextField(verbose_name='Посилання на зображення')),
                ('price_from', models.SmallIntegerField(blank=True, null=True, verbose_name='Ціна від')),
                ('if_show', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
