# Generated by Django 4.1.4 on 2023-01-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey_app', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Текст')),
                ('picture', models.TextField(verbose_name='Посилання на фото')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Загальне',
                'verbose_name_plural': 'Загальні',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ваше ім'я")),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
                ('our_address', models.TextField(blank=True, default='', null=True, verbose_name='Ваша адреса')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
            },
        ),
    ]
