# Generated by Django 4.1.4 on 2023-01-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey_app', '0003_about_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='picture',
            field=models.TextField(blank=True, null=True, verbose_name='Посилання на фото'),
        ),
    ]
