# Generated by Django 4.1.4 on 2023-01-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey_app', '0004_alter_about_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersorder',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар до замовлення'),
        ),
    ]
